name: Deploy to AWS ECS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIA3FLD4U67R6BVCFNE
          aws-secret-access-key: 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
          aws-region: us-east-1
         # registries: 767398029247.dkr.ecr.us-east-1.amazonaws.com/test

      - name: Build and Push Docker Images
        run: |
          docker-compose build
          docker-compose push
