name: Build and Push Docker Compose Images

on:
  push:
    branches:
      - master  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to AWS ECR
      id: login-ecr
      run: |
        aws configure set aws_access_key_id 
        aws configure set aws_secret_access_key 
        aws configure set default.region us-east-1
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y5i3n5q3

    - name: Build and Push Docker Compose Services
      run: |
        docker-compose -f docker-compose.yaml . build
        docker-compose -f docker-compose.yaml . push
