name: Build and Push Docker Images

on:
  push:
    branches:
      - master  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to AWS ECR
      id: login-ecr
      run: |
        aws configure set aws_access_key_id AKIA3FLD4U67R6BVCFNE
        aws configure set aws_secret_access_key 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
        aws configure set default.region us-east-1
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y5i3n5q3

    - name: Build and Push WordPress Docker image
      run: |
        docker build -t wordpress -f word.dockerfile .
        docker push public.ecr.aws/y5i3n5q3/test:latest

    - name: Build and Push MySQL Docker image
      run: |
        docker build -t db -f db.dockerfile .
        docker push public.ecr.aws/y5i3n5q3/test:latest
