name: Build and Push Docker Compose Images

on:
  push:
    branches:
      - testcompose  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to AWS ECR
      id: login-ecr
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        aws configure set default.region us-east-1
        echo '{"credsStore": "ecr-login"}' > /home/runner/.docker/config.json
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y5i3n5q3

    - name: Build and Push Docker Compose Services
      run: |
        docker-compose -f compose/docker-compose.yaml build
        docker-compose -f compose/docker-compose.yaml push
